package com.kuran.android

import com.kuran.android.models.MetinMetrikleri

enum class Sekme {
    ANALIZ,
    KARSILASTIRMA,
    SURELER
}

data class AppState(
    val aktifSekme: Sekme = Sekme.ANALIZ,
    val secilenSureNo: Int = 1,
    val secilenAyetNo: Int = 1,
    val analizMetin: String = "",
    val analizSonucu: MetinMetrikleri? = null,
    val yukleniyor: Boolean = false,
    val hata: String? = null,
    val karsilastirmaMetin: String = "",
    val karsilastirmaSonucu: MetinMetrikleri? = null,
    val karsilastirmaKategori: String = "",
    val secilenKarsilastirmaMetin: String = ""
)

data class Sure(
    val no: Int,
    val adiArapca: String,
    val adiLatince: String,
    val ayetSayisi: Int
)

// Tüm 114 surenin listesi
val surahlar = listOf(
    Sure(1, "الفاتحة", "Fâtihah", 7),
    Sure(2, "البقرة", "Bakara", 286),
    Sure(3, "آل عمران", "Âl-i İmran", 200),
    Sure(4, "النساء", "Nisâ", 176),
    Sure(5, "المائدة", "Mâide", 120),
    Sure(6, "الأنعام", "En'âm", 165),
    Sure(7, "الأعراف", "A'râf", 206),
    Sure(8, "الأنفال", "Enfâl", 75),
    Sure(9, "التوبة", "Tevbe", 129),
    Sure(10, "يونس", "Yûnus", 109),
    Sure(11, "هود", "Hûd", 123),
    Sure(12, "يوسف", "Yûsuf", 111),
    Sure(13, "الرعد", "Rad", 43),
    Sure(14, "إبراهيم", "İbrâhîm", 52),
    Sure(15, "الحجر", "Hicr", 99),
    Sure(16, "النحل", "Nahl", 128),
    Sure(17, "الإسراء", "İsrâ", 111),
    Sure(18, "الكهف", "Kehf", 110),
    Sure(19, "مريم", "Meryem", 98),
    Sure(20, "طه", "Tâ-Hâ", 135),
    Sure(21, "الأنبياء", "Enbiyâ", 112),
    Sure(22, "الحج", "Hac", 78),
    Sure(23, "المؤمنون", "Mu'minûn", 118),
    Sure(24, "النور", "Nûr", 64),
    Sure(25, "الفرقان", "Furkan", 77),
    Sure(26, "الشعراء", "Şuarâ", 227),
    Sure(27, "النمل", "Neml", 93),
    Sure(28, "القصص", "Kasas", 88),
    Sure(29, "العنكبوت", "Ankebût", 69),
    Sure(30, "الروم", "Rum", 60),
    Sure(31, "لقمان", "Lokman", 34),
    Sure(32, "السجدة", "Secde", 30),
    Sure(33, "الأحزاب", "Ahzab", 73),
    Sure(34, "سبأ", "Sebâ", 54),
    Sure(35, "فاطر", "Fâtır", 45),
    Sure(36, "يس", "Yâsîn", 83),
    Sure(37, "الصافات", "Sâffât", 182),
    Sure(38, "ص", "Sâd", 88),
    Sure(39, "الزمر", "Zümer", 75),
    Sure(40, "غافر", "Gâfır", 85),
    Sure(41, "فصلت", "Fussilet", 54),
    Sure(42, "الشورى", "Şûrâ", 53),
    Sure(43, "الزخرف", "Zuhruf", 89),
    Sure(44, "الدخان", "Duhân", 59),
    Sure(45, "الجاثية", "Câsiye", 37),
    Sure(46, "الأحقاف", "Ahkâf", 35),
    Sure(47, "محمد", "Muhammed", 38),
    Sure(48, "الفتح", "Fetih", 29),
    Sure(49, "الحجرات", "Hucurât", 18),
    Sure(50, "ق", "Kâf", 45),
    Sure(51, "الذاريات", "Zâriyât", 60),
    Sure(52, "الطور", "Tûr", 49),
    Sure(53, "النجم", "Necm", 62),
    Sure(54, "القمر", "Kamer", 55),
    Sure(55, "الرحمن", "Rahmân", 78),
    Sure(56, "الواقعة", "Vâkıa", 96),
    Sure(57, "الحديد", "Hadîd", 29),
    Sure(58, "المجادلة", "Mücâdele", 22),
    Sure(59, "الحشر", "Haşr", 24),
    Sure(60, "الممتحنة", "Mumtahine", 13),
    Sure(61, "الصف", "Saff", 14),
    Sure(62, "الجمعة", "Cum'a", 11),
    Sure(63, "المنافقون", "Münâfikûn", 11),
    Sure(64, "التغابن", "Tegâbun", 18),
    Sure(65, "الطلاق", "Talâk", 12),
    Sure(66, "التحريم", "Tahrîm", 12),
    Sure(67, "الملك", "Mülk", 30),
    Sure(68, "القلم", "Kalem", 52),
    Sure(69, "الحاقة", "Hâkka", 52),
    Sure(70, "المعارج", "Ma'ârec", 44),
    Sure(71, "نوح", "Nûh", 28),
    Sure(72, "الجن", "Cin", 28),
    Sure(73, "المزمل", "Müzzemmil", 20),
    Sure(74, "المدثر", "Müddessir", 56),
    Sure(75, "القيامة", "Kıyâme", 40),
    Sure(76, "الإنسان", "İnsan", 31),
    Sure(77, "المرسلات", "Mürselât", 50),
    Sure(78, "النبأ", "Nebe", 40),
    Sure(79, "النازعات", "Nâziât", 46),
    Sure(80, "عبس", "Abese", 42),
    Sure(81, "التكوير", "Tekvîr", 29),
    Sure(82, "الإنفطار", "İnfitâr", 19),
    Sure(83, "المطففين", "Mutaffifîn", 36),
    Sure(84, "الانشقاق", "İnşikâk", 25),
    Sure(85, "البروج", "Burûc", 22),
    Sure(86, "الطارق", "Târık", 17),
    Sure(87, "الأعلى", "A'lâ", 19),
    Sure(88, "الغاشية", "Gâşiye", 26),
    Sure(89, "الفجر", "Fecr", 30),
    Sure(90, "البلد", "Beled", 20),
    Sure(91, "الشمس", "Şems", 15),
    Sure(92, "الليل", "Leyl", 21),
    Sure(93, "الضحى", "Duhâ", 11),
    Sure(94, "الشرح", "Şerh", 8),
    Sure(95, "التين", "Tîn", 8),
    Sure(96, "العلق", "Alak", 19),
    Sure(97, "القدر", "Kadir", 5),
    Sure(98, "البينة", "Beyine", 8),
    Sure(99, "الزلزلة", "Zilzâl", 8),
    Sure(100, "العاديات", "Âdiyât", 11),
    Sure(101, "القارعة", "Kâriâ", 11),
    Sure(102, "التكاثر", "Tekâsur", 8),
    Sure(103, "العصر", "Asr", 3),
    Sure(104, "الهمزة", "Humeze", 9),
    Sure(105, "الفيل", "Fil", 5),
    Sure(106, "قريش", "Kureyş", 4),
    Sure(107, "الماعون", "Mâûn", 7),
    Sure(108, "الكوثر", "Kevser", 3),
    Sure(109, "الكافرون", "Kâfirûn", 6),
    Sure(110, "النصر", "Nasr", 3),
    Sure(111, "المسد", "Mesed", 5),
    Sure(112, "الإخلاص", "İhlas", 4),
    Sure(113, "الفلق", "Felak", 5),
    Sure(114, "الناس", "Nâs", 6)
)
